import type { NextPage } from 'next'
import React, { useState } from 'react'
import Head from 'next/head'
import stylesHome from '../styles/Home.module.css'
import { styled } from '../stitches.config';
import { WeatherCard } from '../components/WeatherCard';

interface WeatherMessages {
  [index: string]: string[];
  blank: string[];
  sunny: string[];
  raining: string[];
  willRain: string[];
}

const Search = styled('input', {
  backgroundColor: '$elementBackground',
  borderRadius: '9999px',
  borderColor: '$elementButtonText',
  fontSize: '13px',
  color: '$elementHeadLine',
  width: '100%',
  padding: '10px 15px',
  '&:hover': {
    backgroundColor: '$elementBackground',
    borderColor: '$elementButtonText',
  },
});

const weatherMessages: WeatherMessages = {
  blank: [
    "Previ nada"
  ],
  sunny: [
    "Vamo pendurar, hoje ta que tá",
    "É pra fazer duas maquinadas tranquilamente",
  ],
  raining: [
    "Corre!",
    "Se não notou até agora, já foi",
  ],
  willRain: [
    "Se tem sorte, vai rapido",
    "Pendura, mas fica de olho",
  ],
};
const weatherTypes = Object.keys(weatherMessages);


function ramdomWeatherType(params:string): string {
  if(params.length > 0){
    const idx = Math.floor(Math.random() * weatherTypes.length);
    return weatherTypes[idx];
  }
  return weatherTypes[0];
}

function ramdomWeatherMessage(weatherType: string): string {
  if(weatherType.length > 0){
    const idx = Math.floor(Math.random() * weatherMessages[weatherType].length);
    return weatherMessages[weatherType][idx];
  }
  return "";
}

async function findCities(params:string) {
  if(!params) 
    return;
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${params}&appid=${process.env.NEXT_PUBLIC_WEATHER_API_KEY}`;

  const resp = await fetch(url);
  if (resp.ok) {
    const data = await resp.json();
    console.log(data);
  } else {
    const data = await resp.json();
    console.log(data);
    return [data.message]
  }
}

const Home: NextPage = () => {
  const [search, setSearch] = useState("");
  const currWeatherType = ramdomWeatherType(search);
  const currWeatherMeesage = ramdomWeatherMessage(currWeatherType);
  
  async function findCities(param:string) {
    if(!param) 
      return;
    const url = `https://api.openweathermap.org/data/2.5/weather?q=${param}&appid=${process.env.NEXT_PUBLIC_WEATHER_API_KEY}`;
  
    const resp = await fetch(url);
    if (resp.ok) {
      const data = await resp.json();
      console.log(data);
    } else {
      const data = await resp.json();
      console.log(data);
      return [data.message]
    }
  }
  function searchLocation(params:React.ChangeEvent<HTMLInputElement>) {
    const foundCities = findCities(search);
    
    setSearch(params.target.value);
  }

  

  return (
    <div className={stylesHome.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={stylesHome.main}>
        <h1 className={stylesHome.title}>
          Bem vindo! Vamos secar algumas roupas?
        </h1>

        <div className={stylesHome.grid}>
          <Search type={'search'} placeholder={'Onde está?'} onChange={searchLocation}/>
        </div>
        <WeatherCard text={currWeatherMeesage} weatherType={currWeatherType}/>
      </main>

      <footer className={stylesHome.footer}>
        
      </footer>
    </div>
  )
}

export default Home
